### ISSUE TITLE
Building from source produces linker errors

### ISSUE THREAD

**Issue by Frityet** [libui-ng/libui-ng#140]
I am on MacOS Montery, compiling with Clang-14. I am building shared

```yaml
FAILED: meson-out/unit
cc  -o meson-out/unit meson-out/unit.p/main.c.o meson-out/unit.p/init.c.o meson-out/unit.p/slider.c.o meson-out/unit.p/spinbox.c.o meson-out/unit.p/label.c.o meson-out/unit.p/button.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error -mmacosx-version-min=10.8 -arch x86_64 -arch arm64 -Wl,-rpath,@loader_path/ meson-out/libui.A.dylib meson-out/libcmocka.a
ld: warning: ignoring file meson-out/libcmocka.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x23 0x31 0x2F 0x31 0x32 0x20 0x20 0x20 )
Undefined symbols for architecture x86_64:
  "__assert_int_equal", referenced from:
      _sliderValueDefaultMin0 in slider.c.o
      _sliderValueDefaultMin1 in slider.c.o
      _sliderSetValue in slider.c.o
      _sliderSetValueOutOfRangeClampLow in slider.c.o
      _sliderSetValueOutOfRangeClampHigh in slider.c.o
      _sliderHasToolTipDefaultTrue in slider.c.o
      _sliderSetHasToolTip in slider.c.o
      ...
  "__assert_string_equal", referenced from:
      _labelText in label.c.o
      _labelTextEmptyString in label.c.o
      _labelSetText in label.c.o
      _labelSetTextEmptyString in label.c.o
      _buttonTextDefault in button.c.o
      _buttonSetText in button.c.o
  "__assert_true", referenced from:
      _unitTestsSetup in main.c.o
      _unitTestSetup in main.c.o
      _initUninit in init.c.o
      _initUninitTwice in init.c.o
  "__cmocka_run_group_tests", referenced from:
      _initRunUnitTests in init.c.o
      _sliderRunUnitTests in slider.c.o
      _spinboxRunUnitTests in spinbox.c.o
      _labelRunUnitTests in label.c.o
      _buttonRunUnitTests in button.c.o
  "__function_called", referenced from:
      _onChangedNoCall in slider.c.o
      _onChangedNoCall in spinbox.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[109/109] Linking target meson-out/cpp-multithread
ninja: build stopped: subcommand failed.
```

**Comment by szanni** [comment]
Did you fix this? The problem is right there in the logs:

> ld: warning: ignoring file meson-out/libcmocka.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x23 0x31 0x2F 0x31 0x32 0x20 0x20 0x20 )

Not sure why your `meson-out/libcmocka.a` is broken though. Maybe just `rm meson-out/libcmocka.a` and build again? Or just remove the entire build directory and configure + build again. I've had weird artifacts with meson in the past.

**Comment by cody271** [comment]
>
>> attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61
>
> Or just remove the entire build directory and configure + build again.
>
Agreed that this looks like a corrupt build AFAICT..

I would start over completely: start with a fresh git clone of the repo, new build directory, configure, etc.

**Comment by Frityet** [comment]
@cody271 @szanni neither worked, even a full reinstall of MacOS produced same results

**Comment by szanni** [comment]
I sadly can't reproduce this.
What architecture are you building on? And what architecture are you targeting?
If you are only targeting `arm64` you might have luck in disabling the `x86_64` build. Very strange.

**Comment by Frityet** [comment]
> I sadly can't reproduce this. What architecture are you building on? And what architecture are you targeting? If you are only targeting `arm64` you might have luck in disabling the `x86_64` build. Very strange.

x86_64

**Comment by Frityet** [comment]
Confirmed, `libcmocka.a` has no symbols

**Comment by cody271** [comment]
You'll have to provide us with _a lot_ more details about your environment to make any sense of this issue..

For example, software version details:
```
$ sw_vers
$ brew --version
$ cc --version
$ meson --version
```

**Comment by Frityet** [comment]
```yaml

**Comment by Frityet** [comment]
```yaml
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79

Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
```

```yaml
Homebrew 3.6.18
Homebrew/homebrew-core (git revision fb6ea18f506; last commit 2023-01-13)
Homebrew/homebrew-cask (git revision 631139ccf9; last commit 2023-01-13)
```

```yaml
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

``` (I used `clang` from homebrew for compilation)

```yaml
Homebrew clang version 15.0.6
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

```

meson:
```yaml
1.0.0
```
